export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const RAW_USER_REPOSITORY = Symbol('RAW_USER_REPOSITORY');
export const ACCOUNT_REPOSITORY = Symbol('ACCOUNT_REPOSITORY');
export const RAW_ACCOUNT_REPOSITORY = Symbol('RAW_ACCOUNT_REPOSITORY');
export const PROFILE_REPOSITORY = Symbol('PROFILE_REPOSITORY');
export const RAW_PROFILE_REPOSITORY = Symbol('RAW_PROFILE_REPOSITORY');
export const FIREBASE_AUTH = Symbol('FIREBASE_AUTH');
